### ISSUE TITLE
continual display of dreams

### ISSUE THREAD

**Issue by bwanaaa** [JoBergs/psycam#1]
Thank you for doing this. I actually got it to work! I know it's not really an issue, but can i get the RPi to keep showing images instead of the terminal output? I installed fbi and it's great for showing images but I have to keep issuing commands from the terminal. I guess I have to modify the psych script to programmatically call fbi with subsequent images. Unless you know of a better and simpler way?

**Comment by JoBergs** [comment]
Hello,

i'm glad you like it!

Don't know fbi, but i had a Kivy touchscreen interface that took photos and displayed them as dreams on the screen. But i don't know in what state Kivy is right now.

Best,
Jo

**Comment by bwanaaa** [comment]
So I looked at Kivy
https://kivy.org/doc/stable/gettingstarted/intro.html
and it seems to be an IDE, 

which is not what i want.

Rather I want to use something like this in your script

```
import Image

image = Image.open('File.jpg')
image.show()
```
I noticed line 66
`PIL.Image.fromarray(np.uint8(frame)).save(dream_path)`

I guess I could add

```
image = Image.open(dream_path)
image.show()
```

after that. The idea is to just have the dreams showing on the monitor while the dreaming is going on in the background.

And, Actually I dont even know why you go to the trouble of saving a time-stamped copy of the input image. I guess that's because it is the standard processing for images from the camera and it's just easier to send an  image file along the same route.

**Comment by JoBergs** [comment]
Picamera is in utils.py make_snapshot. I give it timestamps to make it clear which photo belongs to which dream. That was for an extension i built for a booth.
I still think that can be done with Kivy. Built my booth with it, would have worked with just one big image.

Also, problem with converting images is actually RAM, not CPU, i guess. So overclocking will only help a little.
